/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as UpcomingGdsRouteRouteImport } from './routes/upcoming-gds/route'
import { Route as B2bRouteRouteImport } from './routes/b2b/route'
import { Route as AboutUsRouteRouteImport } from './routes/about-us/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteRouteImport } from './routes/auth/register/route'
import { Route as AuthLoginRouteRouteImport } from './routes/auth/login/route'
import { Route as AuthForgotPasswordRouteRouteImport } from './routes/auth/forgot-password/route'
import { Route as AppProfileRouteRouteImport } from './routes/_app/profile/route'
import { Route as AppNotificationsRouteRouteImport } from './routes/_app/notifications/route'
import { Route as AppDashboardRouteRouteImport } from './routes/_app/dashboard/route'
import { Route as AuthVerifyTokenRouteRouteImport } from './routes/auth/verify/$token/route'
import { Route as AuthResetPasswordTokenRouteRouteImport } from './routes/auth/reset-password/$token/route'
import { Route as AuthGoogleCallbackRouteRouteImport } from './routes/auth/google/callback/route'
import { Route as AppTemplatesNewRouteRouteImport } from './routes/_app/templates/new/route'
import { Route as AppTemplatesIdRouteRouteImport } from './routes/_app/templates/$id/route'
import { Route as AppSessionsNewRouteRouteImport } from './routes/_app/sessions/new/route'
import { Route as AppSessionsIdRouteRouteImport } from './routes/_app/sessions/$id/route'
import { Route as AppResultsSessionIdRouteRouteImport } from './routes/_app/results/$sessionId/route'
import { Route as AppAdminInstructorsRouteRouteImport } from './routes/_app/admin/instructors/route'
import { Route as AppAdminInstructorGdsRouteRouteImport } from './routes/_app/admin/instructor-gds/route'
import { Route as AppAdminB2bRequestsRouteRouteImport } from './routes/_app/admin/b2b-requests/route'
import { Route as AppTemplatesIndexRouteRouteImport } from './routes/_app/templates/index/route'
import { Route as AppSessionsIndexRouteRouteImport } from './routes/_app/sessions/index/route'
import { Route as AppSessionsJoinCodeRouteRouteImport } from './routes/_app/sessions/join/$code/route'
import { Route as AppSessionsIdResultsRouteRouteImport } from './routes/_app/sessions/$id/results/route'
import { Route as AppSessionsIdEvaluateRouteRouteImport } from './routes/_app/sessions/$id/evaluate/route'
import { Route as AppSessionsIdIndexRouteRouteImport } from './routes/_app/sessions/$id/index/route'
import { Route as AppSessionsIdEvaluationsReviewRouteRouteImport } from './routes/_app/sessions/$id/evaluations/review/route'
import { Route as AppSessionsIdEvaluationsIndexRouteRouteImport } from './routes/_app/sessions/$id/evaluations/index/route'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const UpcomingGdsRouteRoute = UpcomingGdsRouteRouteImport.update({
  id: '/upcoming-gds',
  path: '/upcoming-gds',
  getParentRoute: () => rootRouteImport,
} as any)
const B2bRouteRoute = B2bRouteRouteImport.update({
  id: '/b2b',
  path: '/b2b',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRouteRoute = AboutUsRouteRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRouteRoute = AuthRegisterRouteRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRouteRoute = AuthLoginRouteRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRouteRoute = AuthForgotPasswordRouteRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRouteRoute = AppProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRouteRoute = AppNotificationsRouteRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRouteRoute = AppDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AuthVerifyTokenRouteRoute = AuthVerifyTokenRouteRouteImport.update({
  id: '/auth/verify/$token',
  path: '/auth/verify/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordTokenRouteRoute =
  AuthResetPasswordTokenRouteRouteImport.update({
    id: '/auth/reset-password/$token',
    path: '/auth/reset-password/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthGoogleCallbackRouteRoute = AuthGoogleCallbackRouteRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTemplatesNewRouteRoute = AppTemplatesNewRouteRouteImport.update({
  id: '/templates/new',
  path: '/templates/new',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesIdRouteRoute = AppTemplatesIdRouteRouteImport.update({
  id: '/templates/$id',
  path: '/templates/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsNewRouteRoute = AppSessionsNewRouteRouteImport.update({
  id: '/sessions/new',
  path: '/sessions/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsIdRouteRoute = AppSessionsIdRouteRouteImport.update({
  id: '/sessions/$id',
  path: '/sessions/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppResultsSessionIdRouteRoute =
  AppResultsSessionIdRouteRouteImport.update({
    id: '/results/$sessionId',
    path: '/results/$sessionId',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminInstructorsRouteRoute =
  AppAdminInstructorsRouteRouteImport.update({
    id: '/admin/instructors',
    path: '/admin/instructors',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminInstructorGdsRouteRoute =
  AppAdminInstructorGdsRouteRouteImport.update({
    id: '/admin/instructor-gds',
    path: '/admin/instructor-gds',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminB2bRequestsRouteRoute =
  AppAdminB2bRequestsRouteRouteImport.update({
    id: '/admin/b2b-requests',
    path: '/admin/b2b-requests',
    getParentRoute: () => AppRoute,
  } as any)
const AppTemplatesIndexRouteRoute = AppTemplatesIndexRouteRouteImport.update({
  id: '/templates/',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsIndexRouteRoute = AppSessionsIndexRouteRouteImport.update({
  id: '/sessions/',
  path: '/sessions',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsJoinCodeRouteRoute =
  AppSessionsJoinCodeRouteRouteImport.update({
    id: '/sessions/join/$code',
    path: '/sessions/join/$code',
    getParentRoute: () => AppRoute,
  } as any)
const AppSessionsIdResultsRouteRoute =
  AppSessionsIdResultsRouteRouteImport.update({
    id: '/results',
    path: '/results',
    getParentRoute: () => AppSessionsIdRouteRoute,
  } as any)
const AppSessionsIdEvaluateRouteRoute =
  AppSessionsIdEvaluateRouteRouteImport.update({
    id: '/evaluate',
    path: '/evaluate',
    getParentRoute: () => AppSessionsIdRouteRoute,
  } as any)
const AppSessionsIdIndexRouteRoute = AppSessionsIdIndexRouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => AppSessionsIdRouteRoute,
} as any)
const AppSessionsIdEvaluationsReviewRouteRoute =
  AppSessionsIdEvaluationsReviewRouteRouteImport.update({
    id: '/evaluations/review',
    path: '/evaluations/review',
    getParentRoute: () => AppSessionsIdRouteRoute,
  } as any)
const AppSessionsIdEvaluationsIndexRouteRoute =
  AppSessionsIdEvaluationsIndexRouteRouteImport.update({
    id: '/evaluations/',
    path: '/evaluations',
    getParentRoute: () => AppSessionsIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRouteRoute
  '/b2b': typeof B2bRouteRoute
  '/upcoming-gds': typeof UpcomingGdsRouteRoute
  '/dashboard': typeof AppDashboardRouteRoute
  '/notifications': typeof AppNotificationsRouteRoute
  '/profile': typeof AppProfileRouteRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRouteRoute
  '/auth/login': typeof AuthLoginRouteRoute
  '/auth/register': typeof AuthRegisterRouteRoute
  '/sessions/': typeof AppSessionsIndexRouteRoute
  '/templates/': typeof AppTemplatesIndexRouteRoute
  '/admin/b2b-requests': typeof AppAdminB2bRequestsRouteRoute
  '/admin/instructor-gds': typeof AppAdminInstructorGdsRouteRoute
  '/admin/instructors': typeof AppAdminInstructorsRouteRoute
  '/results/$sessionId': typeof AppResultsSessionIdRouteRoute
  '/sessions/$id': typeof AppSessionsIdRouteRouteWithChildren
  '/sessions/new': typeof AppSessionsNewRouteRoute
  '/templates/$id': typeof AppTemplatesIdRouteRoute
  '/templates/new': typeof AppTemplatesNewRouteRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRouteRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRouteRoute
  '/auth/verify/$token': typeof AuthVerifyTokenRouteRoute
  '/sessions/$id/': typeof AppSessionsIdIndexRouteRoute
  '/sessions/$id/evaluate': typeof AppSessionsIdEvaluateRouteRoute
  '/sessions/$id/results': typeof AppSessionsIdResultsRouteRoute
  '/sessions/join/$code': typeof AppSessionsJoinCodeRouteRoute
  '/sessions/$id/evaluations/': typeof AppSessionsIdEvaluationsIndexRouteRoute
  '/sessions/$id/evaluations/review': typeof AppSessionsIdEvaluationsReviewRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRouteRoute
  '/b2b': typeof B2bRouteRoute
  '/upcoming-gds': typeof UpcomingGdsRouteRoute
  '/dashboard': typeof AppDashboardRouteRoute
  '/notifications': typeof AppNotificationsRouteRoute
  '/profile': typeof AppProfileRouteRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRouteRoute
  '/auth/login': typeof AuthLoginRouteRoute
  '/auth/register': typeof AuthRegisterRouteRoute
  '/sessions': typeof AppSessionsIndexRouteRoute
  '/templates': typeof AppTemplatesIndexRouteRoute
  '/admin/b2b-requests': typeof AppAdminB2bRequestsRouteRoute
  '/admin/instructor-gds': typeof AppAdminInstructorGdsRouteRoute
  '/admin/instructors': typeof AppAdminInstructorsRouteRoute
  '/results/$sessionId': typeof AppResultsSessionIdRouteRoute
  '/sessions/$id': typeof AppSessionsIdIndexRouteRoute
  '/sessions/new': typeof AppSessionsNewRouteRoute
  '/templates/$id': typeof AppTemplatesIdRouteRoute
  '/templates/new': typeof AppTemplatesNewRouteRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRouteRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRouteRoute
  '/auth/verify/$token': typeof AuthVerifyTokenRouteRoute
  '/sessions/$id/evaluate': typeof AppSessionsIdEvaluateRouteRoute
  '/sessions/$id/results': typeof AppSessionsIdResultsRouteRoute
  '/sessions/join/$code': typeof AppSessionsJoinCodeRouteRoute
  '/sessions/$id/evaluations': typeof AppSessionsIdEvaluationsIndexRouteRoute
  '/sessions/$id/evaluations/review': typeof AppSessionsIdEvaluationsReviewRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRouteRoute
  '/b2b': typeof B2bRouteRoute
  '/upcoming-gds': typeof UpcomingGdsRouteRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRouteRoute
  '/_app/notifications': typeof AppNotificationsRouteRoute
  '/_app/profile': typeof AppProfileRouteRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRouteRoute
  '/auth/login': typeof AuthLoginRouteRoute
  '/auth/register': typeof AuthRegisterRouteRoute
  '/_app/sessions/': typeof AppSessionsIndexRouteRoute
  '/_app/templates/': typeof AppTemplatesIndexRouteRoute
  '/_app/admin/b2b-requests': typeof AppAdminB2bRequestsRouteRoute
  '/_app/admin/instructor-gds': typeof AppAdminInstructorGdsRouteRoute
  '/_app/admin/instructors': typeof AppAdminInstructorsRouteRoute
  '/_app/results/$sessionId': typeof AppResultsSessionIdRouteRoute
  '/_app/sessions/$id': typeof AppSessionsIdRouteRouteWithChildren
  '/_app/sessions/new': typeof AppSessionsNewRouteRoute
  '/_app/templates/$id': typeof AppTemplatesIdRouteRoute
  '/_app/templates/new': typeof AppTemplatesNewRouteRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRouteRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRouteRoute
  '/auth/verify/$token': typeof AuthVerifyTokenRouteRoute
  '/_app/sessions/$id/': typeof AppSessionsIdIndexRouteRoute
  '/_app/sessions/$id/evaluate': typeof AppSessionsIdEvaluateRouteRoute
  '/_app/sessions/$id/results': typeof AppSessionsIdResultsRouteRoute
  '/_app/sessions/join/$code': typeof AppSessionsJoinCodeRouteRoute
  '/_app/sessions/$id/evaluations/': typeof AppSessionsIdEvaluationsIndexRouteRoute
  '/_app/sessions/$id/evaluations/review': typeof AppSessionsIdEvaluationsReviewRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/b2b'
    | '/upcoming-gds'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/sessions/'
    | '/templates/'
    | '/admin/b2b-requests'
    | '/admin/instructor-gds'
    | '/admin/instructors'
    | '/results/$sessionId'
    | '/sessions/$id'
    | '/sessions/new'
    | '/templates/$id'
    | '/templates/new'
    | '/auth/google/callback'
    | '/auth/reset-password/$token'
    | '/auth/verify/$token'
    | '/sessions/$id/'
    | '/sessions/$id/evaluate'
    | '/sessions/$id/results'
    | '/sessions/join/$code'
    | '/sessions/$id/evaluations/'
    | '/sessions/$id/evaluations/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/b2b'
    | '/upcoming-gds'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/sessions'
    | '/templates'
    | '/admin/b2b-requests'
    | '/admin/instructor-gds'
    | '/admin/instructors'
    | '/results/$sessionId'
    | '/sessions/$id'
    | '/sessions/new'
    | '/templates/$id'
    | '/templates/new'
    | '/auth/google/callback'
    | '/auth/reset-password/$token'
    | '/auth/verify/$token'
    | '/sessions/$id/evaluate'
    | '/sessions/$id/results'
    | '/sessions/join/$code'
    | '/sessions/$id/evaluations'
    | '/sessions/$id/evaluations/review'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/b2b'
    | '/upcoming-gds'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/notifications'
    | '/_app/profile'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/_app/sessions/'
    | '/_app/templates/'
    | '/_app/admin/b2b-requests'
    | '/_app/admin/instructor-gds'
    | '/_app/admin/instructors'
    | '/_app/results/$sessionId'
    | '/_app/sessions/$id'
    | '/_app/sessions/new'
    | '/_app/templates/$id'
    | '/_app/templates/new'
    | '/auth/google/callback'
    | '/auth/reset-password/$token'
    | '/auth/verify/$token'
    | '/_app/sessions/$id/'
    | '/_app/sessions/$id/evaluate'
    | '/_app/sessions/$id/results'
    | '/_app/sessions/join/$code'
    | '/_app/sessions/$id/evaluations/'
    | '/_app/sessions/$id/evaluations/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRouteRoute: typeof AboutUsRouteRoute
  B2bRouteRoute: typeof B2bRouteRoute
  UpcomingGdsRouteRoute: typeof UpcomingGdsRouteRoute
  AppRoute: typeof AppRouteWithChildren
  AuthForgotPasswordRouteRoute: typeof AuthForgotPasswordRouteRoute
  AuthLoginRouteRoute: typeof AuthLoginRouteRoute
  AuthRegisterRouteRoute: typeof AuthRegisterRouteRoute
  AuthGoogleCallbackRouteRoute: typeof AuthGoogleCallbackRouteRoute
  AuthResetPasswordTokenRouteRoute: typeof AuthResetPasswordTokenRouteRoute
  AuthVerifyTokenRouteRoute: typeof AuthVerifyTokenRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upcoming-gds': {
      id: '/upcoming-gds'
      path: '/upcoming-gds'
      fullPath: '/upcoming-gds'
      preLoaderRoute: typeof UpcomingGdsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b2b': {
      id: '/b2b'
      path: '/b2b'
      fullPath: '/b2b'
      preLoaderRoute: typeof B2bRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/verify/$token': {
      id: '/auth/verify/$token'
      path: '/auth/verify/$token'
      fullPath: '/auth/verify/$token'
      preLoaderRoute: typeof AuthVerifyTokenRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password/$token': {
      id: '/auth/reset-password/$token'
      path: '/auth/reset-password/$token'
      fullPath: '/auth/reset-password/$token'
      preLoaderRoute: typeof AuthResetPasswordTokenRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/templates/new': {
      id: '/_app/templates/new'
      path: '/templates/new'
      fullPath: '/templates/new'
      preLoaderRoute: typeof AppTemplatesNewRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates/$id': {
      id: '/_app/templates/$id'
      path: '/templates/$id'
      fullPath: '/templates/$id'
      preLoaderRoute: typeof AppTemplatesIdRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions/new': {
      id: '/_app/sessions/new'
      path: '/sessions/new'
      fullPath: '/sessions/new'
      preLoaderRoute: typeof AppSessionsNewRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions/$id': {
      id: '/_app/sessions/$id'
      path: '/sessions/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof AppSessionsIdRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/results/$sessionId': {
      id: '/_app/results/$sessionId'
      path: '/results/$sessionId'
      fullPath: '/results/$sessionId'
      preLoaderRoute: typeof AppResultsSessionIdRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/instructors': {
      id: '/_app/admin/instructors'
      path: '/admin/instructors'
      fullPath: '/admin/instructors'
      preLoaderRoute: typeof AppAdminInstructorsRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/instructor-gds': {
      id: '/_app/admin/instructor-gds'
      path: '/admin/instructor-gds'
      fullPath: '/admin/instructor-gds'
      preLoaderRoute: typeof AppAdminInstructorGdsRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/b2b-requests': {
      id: '/_app/admin/b2b-requests'
      path: '/admin/b2b-requests'
      fullPath: '/admin/b2b-requests'
      preLoaderRoute: typeof AppAdminB2bRequestsRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates/': {
      id: '/_app/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof AppTemplatesIndexRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions/': {
      id: '/_app/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof AppSessionsIndexRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions/join/$code': {
      id: '/_app/sessions/join/$code'
      path: '/sessions/join/$code'
      fullPath: '/sessions/join/$code'
      preLoaderRoute: typeof AppSessionsJoinCodeRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions/$id/results': {
      id: '/_app/sessions/$id/results'
      path: '/results'
      fullPath: '/sessions/$id/results'
      preLoaderRoute: typeof AppSessionsIdResultsRouteRouteImport
      parentRoute: typeof AppSessionsIdRouteRoute
    }
    '/_app/sessions/$id/evaluate': {
      id: '/_app/sessions/$id/evaluate'
      path: '/evaluate'
      fullPath: '/sessions/$id/evaluate'
      preLoaderRoute: typeof AppSessionsIdEvaluateRouteRouteImport
      parentRoute: typeof AppSessionsIdRouteRoute
    }
    '/_app/sessions/$id/': {
      id: '/_app/sessions/$id/'
      path: ''
      fullPath: '/sessions/$id/'
      preLoaderRoute: typeof AppSessionsIdIndexRouteRouteImport
      parentRoute: typeof AppSessionsIdRouteRoute
    }
    '/_app/sessions/$id/evaluations/review': {
      id: '/_app/sessions/$id/evaluations/review'
      path: '/evaluations/review'
      fullPath: '/sessions/$id/evaluations/review'
      preLoaderRoute: typeof AppSessionsIdEvaluationsReviewRouteRouteImport
      parentRoute: typeof AppSessionsIdRouteRoute
    }
    '/_app/sessions/$id/evaluations/': {
      id: '/_app/sessions/$id/evaluations/'
      path: '/evaluations'
      fullPath: '/sessions/$id/evaluations/'
      preLoaderRoute: typeof AppSessionsIdEvaluationsIndexRouteRouteImport
      parentRoute: typeof AppSessionsIdRouteRoute
    }
  }
}

interface AppSessionsIdRouteRouteChildren {
  AppSessionsIdIndexRouteRoute: typeof AppSessionsIdIndexRouteRoute
  AppSessionsIdEvaluateRouteRoute: typeof AppSessionsIdEvaluateRouteRoute
  AppSessionsIdResultsRouteRoute: typeof AppSessionsIdResultsRouteRoute
  AppSessionsIdEvaluationsIndexRouteRoute: typeof AppSessionsIdEvaluationsIndexRouteRoute
  AppSessionsIdEvaluationsReviewRouteRoute: typeof AppSessionsIdEvaluationsReviewRouteRoute
}

const AppSessionsIdRouteRouteChildren: AppSessionsIdRouteRouteChildren = {
  AppSessionsIdIndexRouteRoute: AppSessionsIdIndexRouteRoute,
  AppSessionsIdEvaluateRouteRoute: AppSessionsIdEvaluateRouteRoute,
  AppSessionsIdResultsRouteRoute: AppSessionsIdResultsRouteRoute,
  AppSessionsIdEvaluationsIndexRouteRoute:
    AppSessionsIdEvaluationsIndexRouteRoute,
  AppSessionsIdEvaluationsReviewRouteRoute:
    AppSessionsIdEvaluationsReviewRouteRoute,
}

const AppSessionsIdRouteRouteWithChildren =
  AppSessionsIdRouteRoute._addFileChildren(AppSessionsIdRouteRouteChildren)

interface AppRouteChildren {
  AppDashboardRouteRoute: typeof AppDashboardRouteRoute
  AppNotificationsRouteRoute: typeof AppNotificationsRouteRoute
  AppProfileRouteRoute: typeof AppProfileRouteRoute
  AppSessionsIndexRouteRoute: typeof AppSessionsIndexRouteRoute
  AppTemplatesIndexRouteRoute: typeof AppTemplatesIndexRouteRoute
  AppAdminB2bRequestsRouteRoute: typeof AppAdminB2bRequestsRouteRoute
  AppAdminInstructorGdsRouteRoute: typeof AppAdminInstructorGdsRouteRoute
  AppAdminInstructorsRouteRoute: typeof AppAdminInstructorsRouteRoute
  AppResultsSessionIdRouteRoute: typeof AppResultsSessionIdRouteRoute
  AppSessionsIdRouteRoute: typeof AppSessionsIdRouteRouteWithChildren
  AppSessionsNewRouteRoute: typeof AppSessionsNewRouteRoute
  AppTemplatesIdRouteRoute: typeof AppTemplatesIdRouteRoute
  AppTemplatesNewRouteRoute: typeof AppTemplatesNewRouteRoute
  AppSessionsJoinCodeRouteRoute: typeof AppSessionsJoinCodeRouteRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRouteRoute: AppDashboardRouteRoute,
  AppNotificationsRouteRoute: AppNotificationsRouteRoute,
  AppProfileRouteRoute: AppProfileRouteRoute,
  AppSessionsIndexRouteRoute: AppSessionsIndexRouteRoute,
  AppTemplatesIndexRouteRoute: AppTemplatesIndexRouteRoute,
  AppAdminB2bRequestsRouteRoute: AppAdminB2bRequestsRouteRoute,
  AppAdminInstructorGdsRouteRoute: AppAdminInstructorGdsRouteRoute,
  AppAdminInstructorsRouteRoute: AppAdminInstructorsRouteRoute,
  AppResultsSessionIdRouteRoute: AppResultsSessionIdRouteRoute,
  AppSessionsIdRouteRoute: AppSessionsIdRouteRouteWithChildren,
  AppSessionsNewRouteRoute: AppSessionsNewRouteRoute,
  AppTemplatesIdRouteRoute: AppTemplatesIdRouteRoute,
  AppTemplatesNewRouteRoute: AppTemplatesNewRouteRoute,
  AppSessionsJoinCodeRouteRoute: AppSessionsJoinCodeRouteRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRouteRoute: AboutUsRouteRoute,
  B2bRouteRoute: B2bRouteRoute,
  UpcomingGdsRouteRoute: UpcomingGdsRouteRoute,
  AppRoute: AppRouteWithChildren,
  AuthForgotPasswordRouteRoute: AuthForgotPasswordRouteRoute,
  AuthLoginRouteRoute: AuthLoginRouteRoute,
  AuthRegisterRouteRoute: AuthRegisterRouteRoute,
  AuthGoogleCallbackRouteRoute: AuthGoogleCallbackRouteRoute,
  AuthResetPasswordTokenRouteRoute: AuthResetPasswordTokenRouteRoute,
  AuthVerifyTokenRouteRoute: AuthVerifyTokenRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
