/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpcomingGdsRouteImport } from './routes/upcoming-gds'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppTemplatesIndexRouteImport } from './routes/_app.templates.index'
import { Route as AppSessionsIndexRouteImport } from './routes/_app.sessions.index'
import { Route as AuthVerifyTokenRouteImport } from './routes/auth.verify.$token'
import { Route as AuthResetPasswordTokenRouteImport } from './routes/auth.reset-password.$token'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth.google.callback'
import { Route as AppTemplatesNewRouteImport } from './routes/_app.templates.new'
import { Route as AppTemplatesIdRouteImport } from './routes/_app.templates.$id'
import { Route as AppSessionsNewRouteImport } from './routes/_app.sessions.new'
import { Route as AppSessionsIdRouteImport } from './routes/_app.sessions.$id'
import { Route as AppResultsSessionIdRouteImport } from './routes/_app.results.$sessionId'
import { Route as AppAdminInstructorsRouteImport } from './routes/_app.admin.instructors'
import { Route as AppAdminInstructorGdsRouteImport } from './routes/_app.admin.instructor-gds'
import { Route as AppSessionsIdIndexRouteImport } from './routes/_app.sessions.$id.index'
import { Route as AppSessionsJoinCodeRouteImport } from './routes/_app.sessions.join.$code'
import { Route as AppSessionsIdResultsRouteImport } from './routes/_app.sessions.$id.results'
import { Route as AppSessionsIdEvaluateRouteImport } from './routes/_app.sessions.$id.evaluate'

const UpcomingGdsRoute = UpcomingGdsRouteImport.update({
  id: '/upcoming-gds',
  path: '/upcoming-gds',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesIndexRoute = AppTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsIndexRoute = AppSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => AppRoute,
} as any)
const AuthVerifyTokenRoute = AuthVerifyTokenRouteImport.update({
  id: '/auth/verify/$token',
  path: '/auth/verify/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordTokenRoute = AuthResetPasswordTokenRouteImport.update({
  id: '/auth/reset-password/$token',
  path: '/auth/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTemplatesNewRoute = AppTemplatesNewRouteImport.update({
  id: '/templates/new',
  path: '/templates/new',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesIdRoute = AppTemplatesIdRouteImport.update({
  id: '/templates/$id',
  path: '/templates/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsNewRoute = AppSessionsNewRouteImport.update({
  id: '/sessions/new',
  path: '/sessions/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsIdRoute = AppSessionsIdRouteImport.update({
  id: '/sessions/$id',
  path: '/sessions/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppResultsSessionIdRoute = AppResultsSessionIdRouteImport.update({
  id: '/results/$sessionId',
  path: '/results/$sessionId',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminInstructorsRoute = AppAdminInstructorsRouteImport.update({
  id: '/admin/instructors',
  path: '/admin/instructors',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminInstructorGdsRoute = AppAdminInstructorGdsRouteImport.update({
  id: '/admin/instructor-gds',
  path: '/admin/instructor-gds',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsIdIndexRoute = AppSessionsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSessionsIdRoute,
} as any)
const AppSessionsJoinCodeRoute = AppSessionsJoinCodeRouteImport.update({
  id: '/sessions/join/$code',
  path: '/sessions/join/$code',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsIdResultsRoute = AppSessionsIdResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppSessionsIdRoute,
} as any)
const AppSessionsIdEvaluateRoute = AppSessionsIdEvaluateRouteImport.update({
  id: '/evaluate',
  path: '/evaluate',
  getParentRoute: () => AppSessionsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/upcoming-gds': typeof UpcomingGdsRoute
  '/dashboard': typeof AppDashboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/admin/instructor-gds': typeof AppAdminInstructorGdsRoute
  '/admin/instructors': typeof AppAdminInstructorsRoute
  '/results/$sessionId': typeof AppResultsSessionIdRoute
  '/sessions/$id': typeof AppSessionsIdRouteWithChildren
  '/sessions/new': typeof AppSessionsNewRoute
  '/templates/$id': typeof AppTemplatesIdRoute
  '/templates/new': typeof AppTemplatesNewRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/auth/verify/$token': typeof AuthVerifyTokenRoute
  '/sessions/': typeof AppSessionsIndexRoute
  '/templates/': typeof AppTemplatesIndexRoute
  '/sessions/$id/evaluate': typeof AppSessionsIdEvaluateRoute
  '/sessions/$id/results': typeof AppSessionsIdResultsRoute
  '/sessions/join/$code': typeof AppSessionsJoinCodeRoute
  '/sessions/$id/': typeof AppSessionsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/upcoming-gds': typeof UpcomingGdsRoute
  '/dashboard': typeof AppDashboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/admin/instructor-gds': typeof AppAdminInstructorGdsRoute
  '/admin/instructors': typeof AppAdminInstructorsRoute
  '/results/$sessionId': typeof AppResultsSessionIdRoute
  '/sessions/new': typeof AppSessionsNewRoute
  '/templates/$id': typeof AppTemplatesIdRoute
  '/templates/new': typeof AppTemplatesNewRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/auth/verify/$token': typeof AuthVerifyTokenRoute
  '/sessions': typeof AppSessionsIndexRoute
  '/templates': typeof AppTemplatesIndexRoute
  '/sessions/$id/evaluate': typeof AppSessionsIdEvaluateRoute
  '/sessions/$id/results': typeof AppSessionsIdResultsRoute
  '/sessions/join/$code': typeof AppSessionsJoinCodeRoute
  '/sessions/$id': typeof AppSessionsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/upcoming-gds': typeof UpcomingGdsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_app/admin/instructor-gds': typeof AppAdminInstructorGdsRoute
  '/_app/admin/instructors': typeof AppAdminInstructorsRoute
  '/_app/results/$sessionId': typeof AppResultsSessionIdRoute
  '/_app/sessions/$id': typeof AppSessionsIdRouteWithChildren
  '/_app/sessions/new': typeof AppSessionsNewRoute
  '/_app/templates/$id': typeof AppTemplatesIdRoute
  '/_app/templates/new': typeof AppTemplatesNewRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/auth/verify/$token': typeof AuthVerifyTokenRoute
  '/_app/sessions/': typeof AppSessionsIndexRoute
  '/_app/templates/': typeof AppTemplatesIndexRoute
  '/_app/sessions/$id/evaluate': typeof AppSessionsIdEvaluateRoute
  '/_app/sessions/$id/results': typeof AppSessionsIdResultsRoute
  '/_app/sessions/join/$code': typeof AppSessionsJoinCodeRoute
  '/_app/sessions/$id/': typeof AppSessionsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/upcoming-gds'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/admin/instructor-gds'
    | '/admin/instructors'
    | '/results/$sessionId'
    | '/sessions/$id'
    | '/sessions/new'
    | '/templates/$id'
    | '/templates/new'
    | '/auth/google/callback'
    | '/auth/reset-password/$token'
    | '/auth/verify/$token'
    | '/sessions/'
    | '/templates/'
    | '/sessions/$id/evaluate'
    | '/sessions/$id/results'
    | '/sessions/join/$code'
    | '/sessions/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/upcoming-gds'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/admin/instructor-gds'
    | '/admin/instructors'
    | '/results/$sessionId'
    | '/sessions/new'
    | '/templates/$id'
    | '/templates/new'
    | '/auth/google/callback'
    | '/auth/reset-password/$token'
    | '/auth/verify/$token'
    | '/sessions'
    | '/templates'
    | '/sessions/$id/evaluate'
    | '/sessions/$id/results'
    | '/sessions/join/$code'
    | '/sessions/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/upcoming-gds'
    | '/_app/dashboard'
    | '/_app/notifications'
    | '/_app/profile'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/_app/admin/instructor-gds'
    | '/_app/admin/instructors'
    | '/_app/results/$sessionId'
    | '/_app/sessions/$id'
    | '/_app/sessions/new'
    | '/_app/templates/$id'
    | '/_app/templates/new'
    | '/auth/google/callback'
    | '/auth/reset-password/$token'
    | '/auth/verify/$token'
    | '/_app/sessions/'
    | '/_app/templates/'
    | '/_app/sessions/$id/evaluate'
    | '/_app/sessions/$id/results'
    | '/_app/sessions/join/$code'
    | '/_app/sessions/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  UpcomingGdsRoute: typeof UpcomingGdsRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  AuthResetPasswordTokenRoute: typeof AuthResetPasswordTokenRoute
  AuthVerifyTokenRoute: typeof AuthVerifyTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upcoming-gds': {
      id: '/upcoming-gds'
      path: '/upcoming-gds'
      fullPath: '/upcoming-gds'
      preLoaderRoute: typeof UpcomingGdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates/': {
      id: '/_app/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof AppTemplatesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions/': {
      id: '/_app/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof AppSessionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/verify/$token': {
      id: '/auth/verify/$token'
      path: '/auth/verify/$token'
      fullPath: '/auth/verify/$token'
      preLoaderRoute: typeof AuthVerifyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password/$token': {
      id: '/auth/reset-password/$token'
      path: '/auth/reset-password/$token'
      fullPath: '/auth/reset-password/$token'
      preLoaderRoute: typeof AuthResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/templates/new': {
      id: '/_app/templates/new'
      path: '/templates/new'
      fullPath: '/templates/new'
      preLoaderRoute: typeof AppTemplatesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates/$id': {
      id: '/_app/templates/$id'
      path: '/templates/$id'
      fullPath: '/templates/$id'
      preLoaderRoute: typeof AppTemplatesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions/new': {
      id: '/_app/sessions/new'
      path: '/sessions/new'
      fullPath: '/sessions/new'
      preLoaderRoute: typeof AppSessionsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions/$id': {
      id: '/_app/sessions/$id'
      path: '/sessions/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof AppSessionsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/results/$sessionId': {
      id: '/_app/results/$sessionId'
      path: '/results/$sessionId'
      fullPath: '/results/$sessionId'
      preLoaderRoute: typeof AppResultsSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/instructors': {
      id: '/_app/admin/instructors'
      path: '/admin/instructors'
      fullPath: '/admin/instructors'
      preLoaderRoute: typeof AppAdminInstructorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/instructor-gds': {
      id: '/_app/admin/instructor-gds'
      path: '/admin/instructor-gds'
      fullPath: '/admin/instructor-gds'
      preLoaderRoute: typeof AppAdminInstructorGdsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions/$id/': {
      id: '/_app/sessions/$id/'
      path: '/'
      fullPath: '/sessions/$id/'
      preLoaderRoute: typeof AppSessionsIdIndexRouteImport
      parentRoute: typeof AppSessionsIdRoute
    }
    '/_app/sessions/join/$code': {
      id: '/_app/sessions/join/$code'
      path: '/sessions/join/$code'
      fullPath: '/sessions/join/$code'
      preLoaderRoute: typeof AppSessionsJoinCodeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions/$id/results': {
      id: '/_app/sessions/$id/results'
      path: '/results'
      fullPath: '/sessions/$id/results'
      preLoaderRoute: typeof AppSessionsIdResultsRouteImport
      parentRoute: typeof AppSessionsIdRoute
    }
    '/_app/sessions/$id/evaluate': {
      id: '/_app/sessions/$id/evaluate'
      path: '/evaluate'
      fullPath: '/sessions/$id/evaluate'
      preLoaderRoute: typeof AppSessionsIdEvaluateRouteImport
      parentRoute: typeof AppSessionsIdRoute
    }
  }
}

interface AppSessionsIdRouteChildren {
  AppSessionsIdEvaluateRoute: typeof AppSessionsIdEvaluateRoute
  AppSessionsIdResultsRoute: typeof AppSessionsIdResultsRoute
  AppSessionsIdIndexRoute: typeof AppSessionsIdIndexRoute
}

const AppSessionsIdRouteChildren: AppSessionsIdRouteChildren = {
  AppSessionsIdEvaluateRoute: AppSessionsIdEvaluateRoute,
  AppSessionsIdResultsRoute: AppSessionsIdResultsRoute,
  AppSessionsIdIndexRoute: AppSessionsIdIndexRoute,
}

const AppSessionsIdRouteWithChildren = AppSessionsIdRoute._addFileChildren(
  AppSessionsIdRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppAdminInstructorGdsRoute: typeof AppAdminInstructorGdsRoute
  AppAdminInstructorsRoute: typeof AppAdminInstructorsRoute
  AppResultsSessionIdRoute: typeof AppResultsSessionIdRoute
  AppSessionsIdRoute: typeof AppSessionsIdRouteWithChildren
  AppSessionsNewRoute: typeof AppSessionsNewRoute
  AppTemplatesIdRoute: typeof AppTemplatesIdRoute
  AppTemplatesNewRoute: typeof AppTemplatesNewRoute
  AppSessionsIndexRoute: typeof AppSessionsIndexRoute
  AppTemplatesIndexRoute: typeof AppTemplatesIndexRoute
  AppSessionsJoinCodeRoute: typeof AppSessionsJoinCodeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppAdminInstructorGdsRoute: AppAdminInstructorGdsRoute,
  AppAdminInstructorsRoute: AppAdminInstructorsRoute,
  AppResultsSessionIdRoute: AppResultsSessionIdRoute,
  AppSessionsIdRoute: AppSessionsIdRouteWithChildren,
  AppSessionsNewRoute: AppSessionsNewRoute,
  AppTemplatesIdRoute: AppTemplatesIdRoute,
  AppTemplatesNewRoute: AppTemplatesNewRoute,
  AppSessionsIndexRoute: AppSessionsIndexRoute,
  AppTemplatesIndexRoute: AppTemplatesIndexRoute,
  AppSessionsJoinCodeRoute: AppSessionsJoinCodeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  UpcomingGdsRoute: UpcomingGdsRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  AuthResetPasswordTokenRoute: AuthResetPasswordTokenRoute,
  AuthVerifyTokenRoute: AuthVerifyTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
